-- #######################################################################################
-- MAIN ENTRY POINT — hyprland.lua
-- All actual config lives in modules/, loaded below via require().
-- Paths are relative to this file's location: ~/.config/hypr/
-- #######################################################################################

-- hl.config({ autogenerated = true }) -- remove/comment this to silence the "autogenerated" warning

require("modules.monitors")
require("modules.env")
require("modules.autostart")
require("modules.input")
require("modules.look")
require("modules.windowrules")
require("modules.binds")
